- name: Ensure anyone can connect to forwarded ports
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^# GatewayPorts'
    line: GatewayPorts yes
  notify: reload ssh

- name: Allow both local and remote (to external machines) port forwards
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^# AllowTcpForwarding'
    line: AllowTcpForwarding yes
  notify: reload ssh