- name: Ensure socat is installed
  apt: 
    name: socat
    state: present

- name: Get socat version
  command: socat -V
  register: socat_version_result

- name: Ensure log file exists
  file:
    path: /var/log/socat.log
    state: touch
    mode: '0644'

- name: Set cronjob to launch socat at reboot
  cron:
    name: "Redirector"
    special_time: reboot
    job: "socat -lf /var/log/socat.log TCP4-LISTEN:443,fork TCP4:{{ c2_ip }}:443 &"
  notify: reboot


- name : Check if socat is running
  command: ps aux | awk '{print $11}' | grep -e "^socat"
  register: socat_running
  ignore_errors: True

- name: Launch socat if not already running
  shell: socat -lf /var/log/socat.log TCP4-LISTEN:443,fork TCP4:{{ c2_ip }}:443 2>&1 &
  when: socat_running is failed