traefik_install_dir: /usr/bin
traefik_binary_url: https://github.com/containous/traefik/releases/download/v2.2.0/traefik_v2.2.0_linux_amd64.tar.gz
traefik_bin_path: "{{ traefik_install_dir }}/"
traefik_base_config_file: /etc/traefik.toml
traefik_provider_config_file: /etc/provider.toml
traefik_base_template: traefik.toml
traefik_provider_template: provider.toml
traefik_systemd_unit_template: traefik.service
traefik_systemd_unit_dest: /etc/systemd/system/traefik.service
traefik_update: no
